import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :gitclass, GitclassWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Gitclass.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure Ueberauth for GitHub OAuth
config :ueberauth, Ueberauth,
  providers: [
    github: {Ueberauth.Strategy.Github, [default_scope: "user:email,read:user"]}
  ]

# Oban Configuration for production
config :gitclass, Oban,
  repo: Gitclass.Repo,
  plugins: [
    Oban.Plugins.Pruner,
    {Oban.Plugins.Cron, crontab: [
      # Refresh commit data every 2 minutes
      {"*/2 * * * *", Gitclass.Workers.RefreshCommitsWorker}
    ]}
  ],
  queues: [
    default: 10,
    github_api: 5,
    import: 3
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
